# 用于生成路由列表
# path React-router 对应的path
# module 要加载的入口模块
# chunk 模块chunk别名, 影响生成的chunk文件名
# exact React-router 对应的exact, 严格匹配路由

- path: /businessA.html
  module: entries/businessA
  chunk: businessA
  exact: true
- path: /businessB.html
  module: entries/businessB
  chunk: businessB
  exact: true
- path: /businessC.html
  module: entries/businessC
  chunk: businessC
  exact: true
- path:
  module: entries/notFound
  chunk: notFound
  exact: false
